### ISSUE TITLE
ImmoScout captcha / bot check prevents crawling

### ISSUE THREAD

**Issue by xu-chris** [adriankumpf/findmeaflat#23]
Unfortunately, while working on the PR #22, I have experienced a blocking behavior in case of ImmoScout. It seems like they have bumped up their crawler detection game.

Any way to resolve this? Would https://www.npmjs.com/package/captcha-solver help?

**Comment by adriankumpf** [comment]
Yeah, that's very unfortunate :/ Even if the captcha can be bypassed, it will be a cat-and-mouse game. I'll have to take a look at that package.
