### ISSUE TITLE
Finds new offers only after restart

### ISSUE THREAD

**Issue by chbndrhnns** [adriankumpf/findmeaflat#6]
I need to restart the docker container multiple times a day to make it catch up new offers. Is there something I could do to troubleshoot this behavior? I would prefer if this restart is not necessary...

**Comment by adriankumpf** [comment]
The configured interval is 1 hour. Restarting should not be necessary. During the first run the crawler uses pagination to scrape all listings. Subsequents run then only scrape the first listings page. Therefore you could check whether you've actually sorted by newest listings. If that is the case could you please verify that the scraping of all configured pages actually finishes?

**Comment by chbndrhnns** [comment]
I found my issue: not sorting by last recently added. Sorry for bothering you.

**Comment by adriankumpf** [comment]
Okay, cool. You're not the first one to miss it :) I'll try to improve the README.
