### ISSUE TITLE
429 Too many requests after starting the bot 

### ISSUE THREAD

**Issue by chbndrhnns** [adriankumpf/findmeaflat#7]
Is there a way to respect Telegram's message limits in your bot? They are described in https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this:

  > When sending messages inside a particular chat, avoid sending more than one message per second. We may allow short bursts that go over this limit, but eventually you'll begin receiving 429 errors. If you're sending bulk notifications to multiple users, the API will not allow more than 30 messages per second or so. Consider spreading out notifications over large intervals of 8—12 hours for best results. Also note that your bot will not be able to send more than 20 messages per minute to the same group.

**Comment by adriankumpf** [comment]
Check out the `throttle-telegram-requests` (9c29725) branch. I recommend you to tweak the delay between messages though. I chose 1 second which works but it's really annoying to permanently receive push notifications over a period of a couple of minutes.
